apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: "adsfasdf"
  namespace: "guru-tenant"
spec:
  type: Python
  sparkVersion: 3.3.1
  mode: cluster
  image: "gcr.io/mapr-252711/spark-py-3.3.1:v3.3.1"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "dtap://nfs1/hive_test3.py"
  restartPolicy:
    type: Never
  imagePullSecrets:
    - imagepull
  driver:
    labels:
      version: 3.3.1
      hpecp.hpe.com/dtap: hadoop2-job
    cores: 1
    coreLimit: "1"
    memory: 512m
    serviceAccount: hpe-guru-tenant
  executor:
    labels:
      version: 3.3.1
      hpecp.hpe.com/dtap: hadoop2-job
    cores: 1
    coreLimit: "1"
    memory: 512m
    serviceAccount: hpe-guru-tenant
    instances: 1
  sparkConf:
    spark.eventLog.enabled: "true"
    spark.hadoop.fs.dtap.impl.disable.cache: "false"
    spark.hadoop.fs.AbstractFileSystem.dtap.impl: com.bluedata.hadoop.bdfs.BdAbstractFS
    spark.hadoop.fs.dtap.impl: com.bluedata.hadoop.bdfs.Bdfs
    spark.driver.extraClassPath: local:///opt/bdfs/bluedata-dtap.jar
    spark.executor.extraClassPath: local:///opt/bdfs/bluedata-dtap.jar
  deps:
    jars:
      - local:///opt/bdfs/bluedata-dtap.jar
