apiVersion: sparkoperator.hpe.com/v1beta2
kind: SparkApplication
metadata:
  name: hive-test-2
  namespace: guru-tenant
  # resourceVersion: "710557"
spec:
  # deps:
    # jars:
      # - local:///opt/bdfs/bluedata-dtap.jar
  driver:
    coreLimit: "1"
    cores: 1
    labels:
      # hpecp.hpe.com/dtap: hadoop2-job
      version: 3.3.1
    memory: 2G
    serviceAccount: hpe-guru-tenant
    # serviceAccount: airflow-worker
    # volumeMounts:
    #   - mountPath: /opt/mapr/spark/sparkhs-eventlog-storage
    #     name: sparkhs-eventlog-storage
      # - mountPath: /opt/mapr/spark/file-storage
      # - mountPath: /opt/mapr/spark/work-dir
      #   name: spark-file-storage
    # mainApplicationFile: /opt/mapr/spark/file-storage/hive_test3.py
  executor:
    coreLimit: "2"
    cores: 2
    instances: 2
    labels:
    #   # hpecp.hpe.com/dtap: hadoop2-job
      version: 3.3.1
    memory: 2G
    serviceAccount: hpe-guru-tenant
    # serviceAccount: airflow-worker
    # volumeMounts:
    #   # - mountPath: /opt/mapr/spark/sparkhs-eventlog-storage
    #   #   name: sparkhs-eventlog-storage
    #   - mountPath: /opt/mapr/spark/file-storage
    #     name: spark-file-storage
  image: gcr.io/mapr-252711/spark-py-3.3.1:v3.3.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - imagepull
  mainApplicationFile: s3a://imgr-buc-inner/spark-file/t0_external.py
  mode: cluster
  restartPolicy:
    type: Never
  sparkConf:
    spark.eventLog.enabled: "true"
    spark.hadoop.fs.s3a.endpoint: http://114.202.139.172:8888
    spark.hadoop.fs.s3a.access.key: "minioadmin"
    spark.hadoop.fs.s3a.secret.key: "minioadmin"
    spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.mapr.user.secret: hpe-autotix-generated-secret-iocwgg
  sparkVersion: 3.3.1
  type: Python
  # volumes:
  #   - name: sparkhs-eventlog-storage
  #     persistentVolumeClaim:
  #       claimName: sparkhs-pvc
    # - name: spark-file-storage
    #   persistentVolumeClaim:
    #     claimName: airflow-pvc